namespace: mgmt

stores:
  - name: mgmt-prod
    namespace: mgmt
    token:
      name: doppler-token-mgmt-prod
      namespace: mgmt

secrets:
  - name: cloudflare-api-token-secret
    namespace: cert-manager
    secretStoreName: mgmt-prod
    data:
    - secretKey: api-token
      remoteRef:
        key: CLOUDFLARE_CLUSTERISSUER_API_TOKEN
  - name: doppler-token-mgmt-prod
    namespace: mgmt
    secretStoreName: mgmt-prod
    data:
    - secretKey: dopplerToken
      remoteRef:
        key: DOPPLER_TOKEN_MGMT_PROD
  - name: argocd-repo-creds-ssh-creds
    namespace: argocd
    secretStoreName: mgmt-prod
    data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: ARGOCD_SSH_KEY
  - name: exoscale-sos-secret
    namespace: longhorn-system
    secretStoreName: mgmt-prod
    dataFrom:
    - find:
        name:
          regexp: "EXOSCALE_.*"
      rewrite:
      - regexp:
          source: "EXOSCALE_(.+)"
          target: "$1"
