{{- range .Values.stores }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $.Values.namespace | default $.Release.Namespace }}
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: {{ .token.name }}
            key: dopplerToken
            namespace: {{ .token.namespace | default .namespace | default $.Values.namespace | default $.Release.Namespace }}
{{- end -}}